FROM python:3.8-slim-buster

RUN mkdir /opt/ml
RUN mkdir /opt/ml/input
RUN mkdir /opt/ml/input/code
RUN mkdir /opt/ml/input/data
RUN mkdir /opt/ml/output
RUN mkdir /opt/ml/output/metric
RUN mkdir /opt/ml/model

COPY requirements-serve.txt /opt/ml/input/code

WORKDIR /opt/ml/input/code
RUN pip install -r requirements-serve.txt

ENTRYPOINT [ "/bin/bash" ]