# Source: https://pre-commit.com/
# Inspiration: https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e
# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/PyCQA/bandit  # https://github.com/PyCQA/bandit
    rev: '1.7.5' # Updated 14.10.2022
    hooks:
      - id: bandit
        args: [--skip, "B101", --recursive, clumper]
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # Updated 14.10.2022
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Updated 14.10.2022
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy