# Source: https://pre-commit.com/
# Inspiration: https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e
# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.7' # Updated 01.02.2024
    hooks:
      - id: bandit
        args: [ --skip, "B101", --recursive, clumper ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0' # Updated 01.02.2024
    hooks:
      - id: mypy
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15 # Updated 01.02.2024
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format