[tool.poetry]
name = "rdfier"
version = "1.0.0"
description = "Application to turn csv data into a rdf graph"
authors = ["poepperl <luca.poepperl@gmail.com>"]
readme = "README.md"
packages = [
    { include = "src/rdfier" },
]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.27.2"
rdflib = "^7.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
